server:
  port: 6325
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    appname: boot-es
    leaseRenewalIntervalInSeconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    instance-id: 127.0.0.1:6325

spring:
  elasticsearch:
    jest:
      uris: http://192.144.176.99:9200  # ES服务器地址
      read-timeout: 5000s
