server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    appname: eboot-provider
    leaseRenewalIntervalInSeconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
      name: boot-provider
